# Docker >= 17.05.0-ce allows using build-time args (ARG) in FROM (#31352).
# https://github.com/moby/moby/releases/tag/v17.05.0-ce
ARG OS_NAME=fedora
ARG OS_VERSION=25
ARG ARCH=aarch64
FROM multiarch/${OS_NAME}:${OS_VERSION}-${ARCH}

# Test with non-root user.
ENV TEST_USER test
ENV WORK_DIR "/build"

RUN uname -a
RUN echo -e "deltarpm=0\ninstall_weak_deps=0\ntsflags=nodocs" >> /etc/dnf/dnf.conf
RUN dnf -y update
RUN dnf -y --allowerasing install \
  gcc \
  git \
  make \
  redhat-rpm-config \
  sudo
# Create test user and the environment
RUN useradd "${TEST_USER}"
WORKDIR "${WORK_DIR}"
COPY . .
RUN chown -R "${TEST_USER}:${TEST_USER}" "${WORK_DIR}"

# Enable sudo without password for convenience.
RUN echo "${TEST_USER} ALL = NOPASSWD: ALL" >> /etc/sudoers

USER "${TEST_USER}"
